### ISSUE TITLE
[req] what version of json schema, keywords supported? 

### ISSUE THREAD

**Issue by spacether** [berislavlopac/momoa#1]
what version of json schema is implemented , keywords supported?

**Comment by berislavlopac** [comment]
It's using [Statham](https://statham-schema.readthedocs.io/) underneath, which is [supporting the Draft 6 specification](https://statham-schema.readthedocs.io/en/latest/compatibility.html).

**Comment by spacether** [comment]
Thanks! How about putting that info in the readme?

**Comment by berislavlopac** [comment]
Fair point, will do with the next release!

**Comment by berislavlopac** [comment]
Resolved in https://github.com/berislavlopac/momoa/releases/tag/0.2.0
